### ISSUE TITLE
Application of Your Method on Datasets Without Uncertainty Labels

### ISSUE THREAD

**Issue by coisino** [Jianf-Wang/NP-SemiSeg#1]
Hello,

I am reaching out to inquire whether this method can be applied to image datasets that do not contain uncertainty labels. I noticed that the two datasets utilized in your paper both contain labels denoting uncertainty. I am interested to know if this approach can still be beneficial in contexts where such labels are not available.

Thank you for your time and consideration.

**Comment by Jianf-Wang** [comment]
Hi, thanks for your interest in this work. This method does not need any uncertainty labels for supervision during training, and you can directly apply it to any image datasets (e.g., medical datasets). The uncertainty maps shown in the paper are predicted by the neural processes head, rather than uncertainty labels.

**Comment by coisino** [comment]
Could you please guide me on how to view or extract the uncertainty maps corresponding to the prediction results in your framework?

**Comment by Jianf-Wang** [comment]
Hi, you can set "forward_times" in np_head.py properly (the default value is 5). During testing, for an input image, you will get 5 prediction maps, and you can calculate entropy (uncertainty) using them. Then, you can set an uncertainty threshold (e.g., 0.3). If the uncertainty is lower than this, you can assume the model is certain about its prediction. You may only plot the pixels whose uncertainty is higher than 0.3, indicating the model is uncertain about these predicted pixels.
